ci: manage ecr repository completely outside of tf

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -17,6 +17,7 @@ DEPLOY_FUNCTIONS_ONLY="${DEPLOY_FUNCTIONS_ONLY:-false}"
 AWS_ECR_ENABLE="${AWS_ECR_ENABLE:-false}"
 AWS_ECR_REPUSH="${AWS_ECR_REPUSH:-false}"
 AWS_ECR_DONT_BUILD_FROM_CACHE="${AWS_ECR_DONT_BUILD_FROM_CACHE:-false}"
+AWS_ECR_REPO_NAME="${TF_VAR_app_name}-${ENVIRONMENT}"
 DOCKER_COMPOSE_DEPLOY="docker-compose -f docker-compose.deploy.yml"
 set -e
 
@@ -127,7 +128,6 @@ write_infrastructure_secrets() {
     info "===> ${output_var}: retrieved"
     write_secret "$secret_value" "$output_var"
   done
-  write_secret "$(get_existing_ecr_repository)" "ecr_repository"
 }
 
 push_app_to_ecr() {
@@ -170,34 +170,32 @@ get_existing_ecr_repository() {
 }
 
 deploy_serverless_infrastructure() {
-  delete_ecr_from_state_to_prevent_long_image_build_times() {
-    grep -Eiq '^true$' <<< "$AWS_ECR_ENABLE" || return 0
+  create_ecr_if_desired() {
+    grep -Eiq '^true$' <<< "$AWS_ECR_ENABLE"  || return 0
 
-    info "Removing AWS ECR from Terraform state to prevent long Docker image build times"
-    $DOCKER_COMPOSE_DEPLOY run --rm delete-ecr-from-state-"$ENVIRONMENT" || true
-  }
-
-  ecr_repository_not_exists() {
-    test -z "$(get_existing_ecr_repository)"
+    if test -z "$(get_existing_ecr_repository)"
+    then
+      $DOCKER_COMPOSE_DEPLOY run --rm aws ecr create-repository \
+        --repository-name "$AWS_ECR_REPO_NAME" &&
+      write_secret "ecr_repository" "$(get_existing_ecr_repository)"
+    fi
   }
 
   export $(get_aws_credentials)
-  aws_ecr_enabled="${AWS_ECR_ENABLE}"
-  if ! ecr_repository_not_exists
-  then
-    aws_ecr_enabled=false
-  fi
   info "Deploying serverless infrastructure."
-  $DOCKER_COMPOSE_DEPLOY run --rm \
-    -e TF_VAR_aws_ecr_enable="$aws_ecr_enabled" \
-    deploy-serverless-infra-"$ENVIRONMENT" &&
+  if ! $DOCKER_COMPOSE_DEPLOY run --rm deploy-serverless-infra-"$ENVIRONMENT"
+  then
+    fail "Failed to deploy infrastructure"
+    exit 1
+  fi
   write_infrastructure_secrets &&
   if test "$ENVIRONMENT" == "production"
   then
     $DOCKER_COMPOSE_DEPLOY build deploy-serverless-domain-production &&
     $DOCKER_COMPOSE_DEPLOY run --rm deploy-serverless-domain-production
   fi &&
-  delete_ecr_from_state_to_prevent_long_image_build_times
+
+  create_ecr_if_desired
 }
 
 deploy_serverless_functions() {
